import sys


def generate_sine_table(steps=360):
    """Generate a sine table with the specified number of steps."""
    import math

    sine_table = []
    for i in range(steps):
        angle = (2 * math.pi / steps) * i
        sine_value = math.sin(angle)
        sine_table.append(sine_value)

    return sine_table


def get_sine_lines(steps=360):
    template = """
/**
    * This file is automatically generated through python.
    *
    * If you feel the urge to change anything in it, I recommend
    * to resist and changing the python script which generates it instead.
    *
    * python file: "sine_table.py"
    */

#include "sine_table.h"

alignas(32) const float sine_table[SINE_TABLE_SIZE] = {
    <sine_values>
};
"""

    sine_values = generate_sine_table(steps)
    sine_values_str = ",\n    ".join(f"{value:.8f}f" for value in sine_values)

    filled_template = template.replace("<sine_values>", sine_values_str)
    return filled_template.strip().splitlines(keepends=True)


def main(output_file=None):
    # if output_file is None, write to console
    lines = get_sine_lines(1024)
    if output_file:
        with open(output_file, "w") as f:
            f.writelines(lines)
    else:
        for line in lines:
            print(line, end="")
        print()


if __name__ == "__main__":
    # output file is given on first argument
    output_file = sys.argv[1] if len(sys.argv) > 1 else None

    main(output_file)
